export const GAME_CONFIG = {
  ALIEN_SPAWN_INTERVAL: 15000,
  ALIEN_CAP: 3,
  SHIELD_SPAWN_CHANCE: 0.7,
  SHIELD_SPAWN_INTERVAL: 10000,
  LASER_SPAWN_CHANCE: 0.3,
  LASER_SPAWN_INTERVAL: 15000,
  AURA_SPAWN_CHANCE: 0.25,
  AURA_SPAWN_INTERVAL: 18000,
  ROCKET_SPAWN_CHANCE: 0.25,
  ROCKET_SPAWN_INTERVAL: 20000,
  HEALTH_SPAWN_CHANCE: 0.4,
  HEALTH_SPAWN_INTERVAL: 12000,
} as const;

export const ENTITY_CONFIG = {
  BULLET: {
    SPEED: 7,
    LIFE: 100,
  },
  ASTEROID: {
    SPEED_FACTOR: 4,
  },
  POWERUP: {
    SPEED_FACTOR: 1,
    RADIUS: 15,
  },
  ALIEN: {
    RADIUS: 15,
    SPEED_FACTOR: 2,
    SHOOT_COOLDOWN_BASE: 60,
    SHOOT_COOLDOWN_RANGE: 40,
    TARGET_DIST_MAX: 400,
    ASTEROID_AVOID_DIST: 60,
  },
  ROCKET: {
    SPEED: 5,
    LIFE: 400,
    STRAIGHT_FRAMES: 30,
    HOME_RANGE: 250,
    TURN_RATE: 0.08,
    SHOT_COUNT: 5,
  },
  SHIP: {
    RADIUS: 12,
    FRICTION: 0.98,
    ROTATION_SPEED: 0.07,
    THRUST_POWER: 0.2,
    SHOOT_COOLDOWN: 15,
    MAX_HP: 100,
    LASER_SHOT_COUNT: 10,
    LASER_TIMER: 200,
    AURA_SHOT_COUNT: 10,
    SHIELD_DURATION: 2400,
    HEALTH_BAR_TIMER: 60,
  },
} as const;

export const SCORING = {
  ASTEROID_BASE: 10,
  ALIEN: 100,
  SHIELD: 50,
  LASER: 75,
  AURA: 75,
  ROCKET: 75,
  HEALTH_SMALL: 50,
  HEALTH_LARGE: 75,
} as const;

export const SHIELD_DAMAGE = {
  BULLET: 300,
  ALIEN_BODY: 600,
  ASTEROID: 300,
} as const;

// Collision category bits
export const CAT_PLAYER = 1 << 0;
export const CAT_ASTEROID = 1 << 1;
export const CAT_PLAYER_BULLET = 1 << 2;
export const CAT_ENEMY_BULLET = 1 << 3;
export const CAT_ENEMY = 1 << 4;
export const CAT_PICKUP = 1 << 5;
